package us.florent;

import java.awt.Component;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;


public class distDialog extends javax.swing.JDialog {

//    private static String value = "";
    private static List<String> value;
    private static distDialog dialog;

    /** Creates new form distDialog */
    public distDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public static List<String> showDialog(Component frameComp,
                                    Component locationComp,
                                    String labelText,
                                    String title,
                                    List<String> possibleValues,
                                    List<String> initialValues) {

        java.awt.Frame frame = JOptionPane.getFrameForComponent(frameComp);

        dialog = new distDialog(frame, true);
        DefaultListModel model = (DefaultListModel)dialog.jList1.getModel();
        for(String val : possibleValues)
            model.addElement(val);
        model = (DefaultListModel)dialog.jList2.getModel();
        for(String val : initialValues)
            model.addElement(val);
        dialog.setLocationRelativeTo(locationComp);
        dialog.setVisible(true);
        return value;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jSplitPane1.setDividerLocation(250);

        jList2.setModel(new javax.swing.DefaultListModel());
        jList2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList2MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList2);

        jSplitPane1.setRightComponent(jScrollPane1);

        jList1.setModel(new javax.swing.DefaultListModel());
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jList1);

        jSplitPane1.setLeftComponent(jScrollPane2);

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
                        .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        DefaultListModel model = (DefaultListModel)jList2.getModel();
        var ret = new ArrayList<String>();
        for(int i = 0; i < model.getSize(); i++) {
            ret.add(model.get(i).toString());
            //if(i < (model.getSize() - 1))
                //ret.append(", ");
        }
        value = ret;
        dialog.setVisible(false);
    }

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {
        if(evt.getClickCount() == 2) {
            String sel = (String) jList1.getSelectedValue();
            ((DefaultListModel)jList1.getModel()).removeElement(sel);
            ((DefaultListModel)jList2.getModel()).addElement(sel);

        }
    }

    private void jList2MouseClicked(java.awt.event.MouseEvent evt) {
        if(evt.getClickCount() == 2) {
            String sel = (String) jList2.getSelectedValue();
            ((DefaultListModel)jList2.getModel()).removeElement(sel);
            ((DefaultListModel)jList1.getModel()).addElement(sel);

        }
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        dialog.setVisible(false);
    }


    // Variables declaration - do not modify
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JList jList1;
    private javax.swing.JList jList2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration

}
