/*
 * speciesEdit.java
 *
 */
package us.florent;

import com.mongodb.client.model.ReplaceOptions;
import org.bson.Document;

import java.awt.Color;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.List;
import java.util.Set;
import java.util.TreeSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.Collectors;
import javax.swing.DefaultCellEditor;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author florent Charpin
 */
public class speciesEdit extends javax.swing.JFrame {

    private final genReef35 db = new genReef35();
    private List<String> dist_a;
    private List<String> locations;
    private List<String> types;
    private genReef35.Species node;

    private int row = 0;

    class RowRenderer extends javax.swing.table.DefaultTableCellRenderer {

        final Color color = new Color(247, 245, 213);
        String head = null;

        @Override
        public java.awt.Component getTableCellRendererComponent(javax.swing.JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {

            if(row % 2 == 0) {
                setBackground(Color.white);
            } else {
                setBackground(color);
            }
            return super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

        }
    }

    class CustomTableModel extends DefaultTableModel {

        String[] hearders = new String[]{"Thumb", "Location", "Type", "Depth", "Comment"};
        Class[] types = new Class[]{
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class};
        boolean[] canEdit = new boolean[]{true, true, true, true, true};

        CustomTableModel() {
            addColumn(hearders[0]);
            addColumn(hearders[1]);
            addColumn(hearders[2]);
            addColumn(hearders[3]);
            addColumn(hearders[4]);
            for(int i = 0; i < 30; i++) {
                addRow(new Object[0]);
            }
        }

        @Override
        public Class getColumnClass(int columnIndex) {
            return types[columnIndex];
        }

        @Override
        public boolean isCellEditable(int rowIndex, int columnIndex) {
            return canEdit[columnIndex];
        }
    }

    public speciesEdit() throws IOException {
        Logger mongoLogger = Logger.getLogger( "org.mongodb.driver" );
        mongoLogger.setLevel(Level.SEVERE);
        initComponents();
        initDB();
        populateTable(null);
        setLocationRelativeTo(null);
        fillValues();
        //node = new genReef35.Species();
        jTable1.getModel().setValueAt("1", 0, 0);
        thumbTextField.setText("1");
    }

    private void initDB() throws IOException {
        //genReef35 reef = new genReef35();
        db.basepathIndexAll = "/home/fc/web/reef4";
        db.buildAllData("/config/reeflist4.xml", 0);

        dist_a = db.species_collection.getAllSpecies().stream().flatMap(s -> s.dist().stream()).sorted().distinct().collect(Collectors.toList());
        node = null;
        locations =  db.species_collection.getAllSpecies().stream().flatMap(s -> s.photo().stream()).map(p -> p.location()).sorted().distinct().collect(Collectors.toList());
        types =  db.species_collection.getAllSpecies().stream().flatMap(s -> s.photo().stream()).filter(p -> p.type() != null).map(p -> p.type()).sorted().distinct().collect(Collectors.toList());
        locations.add(0, "");
        types.add(0, "");
    }

    private void fillValues() {
        Set<String> name = new TreeSet<>();
        String[] list = db.species_collection.getAllSpecies().stream().map(s->s.genus()).sorted().distinct().collect(Collectors.toList()).toArray(new String[0]);

        jComboBox1.setModel(new DefaultComboBoxModel<>(list));

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        IDTextField = new javax.swing.JTextField();
        loadButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        NameTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        sciTextField = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        depth1TextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        depth2TextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        sizeTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        disp1TextField = new javax.swing.JTextField();
        thumbTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        disp2TextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        thumb2TextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        disp3TextField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        thumb3TextField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        akaTextField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        asnTextField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        distTextField = new javax.swing.JTextField();
        distSelect = new javax.swing.JButton();
        jTextField16 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        noteTextField = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuNew = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        jMenuItem5.setText("Move Up");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem5);

        jMenuItem6.setText("Move Down");
        jPopupMenu1.add(jMenuItem6);

        jMenuItem7.setText("Insert");
        jPopupMenu1.add(jMenuItem7);

        jMenuItem8.setText("Remove");
        jPopupMenu1.add(jMenuItem8);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID");

        IDTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDTextFieldActionPerformed(evt);
            }
        });
        IDTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                IDTextFieldFocusLost(evt);
            }
        });

        loadButton.setText("Load");
        loadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadButtonActionPerformed(evt);
            }
        });

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Name");

        NameTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                NameTextFieldFocusLost(evt);
            }
        });
        NameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameTextFieldActionPerformed(evt);
            }
        });

        jLabel3.setText("Sci. Name");

        jComboBox1.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Depth");

        depth1TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depth1TextFieldActionPerformed(evt);
            }
        });

        jLabel5.setText("-");

        depth2TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depth2TextFieldActionPerformed(evt);
            }
        });

        jLabel6.setText("Size");

        sizeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sizeTextFieldActionPerformed(evt);
            }
        });

        jLabel7.setText("Disp 1");

        thumbTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thumbTextFieldActionPerformed(evt);
            }
        });

        jLabel8.setText("thumb");

        jLabel9.setText("Disp 2");

        jLabel10.setText("thumb");

        thumb2TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thumb2TextFieldActionPerformed(evt);
            }
        });

        jLabel11.setText("Disp 3");

        jLabel12.setText("thumb");

        thumb3TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thumb3TextFieldActionPerformed(evt);
            }
        });

        jLabel13.setText("AKA");

        jLabel14.setText("Alt. Sci.");

        jLabel15.setText("Dist.");

        distSelect.setText("...");
        distSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                distSelectActionPerformed(evt);
            }
        });

        jTextField16.setEditable(false);

        jTable1.setModel(new CustomTableModel());
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        jTable1.setColumnSelectionAllowed(true);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTable1MouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jLabel16.setText("Note");

        jMenu1.setText("File");

        jMenuNew.setText("New");
        jMenuNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuNewActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuNew);

        jMenuItem1.setText("Exit");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jMenuItem2.setText("Reload");
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("Diff");
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("New Location");
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(26, 26, 26)
                                                                .addComponent(jLabel1))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jLabel4))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                                                                        .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))))
                                                .addGap(13, 13, 13))
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel15)
                                                        .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                                                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                                                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                                                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                                                        .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(depth1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(5, 5, 5)
                                                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(5, 5, 5)
                                                                .addComponent(depth2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(jLabel6)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(sizeTextField))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                                        .addComponent(sciTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
                                                                                        .addComponent(IDTextField, javax.swing.GroupLayout.Alignment.TRAILING))
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addGroup(layout.createSequentialGroup()
                                                                                                .addComponent(loadButton)
                                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addComponent(saveButton))
                                                                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                        .addComponent(NameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(0, 0, Short.MAX_VALUE)))
                                                .addGap(14, 14, 14))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(distTextField)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(distSelect)
                                                .addContainerGap())
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(disp3TextField)
                                                        .addComponent(disp2TextField)
                                                        .addComponent(disp1TextField))
                                                .addGap(10, 10, 10)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel8)
                                                        .addComponent(jLabel10)
                                                        .addComponent(jLabel12))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(thumbTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(thumb2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(thumb3TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addContainerGap())
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(asnTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(akaTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
                                                        .addComponent(noteTextField, javax.swing.GroupLayout.Alignment.LEADING))
                                                .addContainerGap())))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 659, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField16, javax.swing.GroupLayout.DEFAULT_SIZE, 635, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                                                .addGap(425, 425, 425)))
                                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {NameTextField, sciTextField});

        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(loadButton, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(IDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                                        .addComponent(jLabel2)
                                        .addComponent(NameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(sciTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4)
                                        .addComponent(depth1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5)
                                        .addComponent(depth2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6)
                                        .addComponent(sizeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(disp1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(2, 2, 2)
                                                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(disp2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel9))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(disp3TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel11))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel13)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(akaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(asnTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jLabel14))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(noteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jLabel16)))))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(thumbTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(jLabel8))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(25, 25, 25)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(thumb2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jLabel10))))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(thumb3TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel12))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(distTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel15))
                                        .addComponent(distSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {

        if(IDTextField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "No ID entered, cannot save",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        //int ok = JOptionPane.showConfirmDialog(null, "Save species?" , "Save trade", JOptionPane.OK_CANCEL_OPTION);

        //if(ok == 2)
          //  return;

        Document doc = new Document();
        doc.put("id", IDTextField.getText().trim());
        doc.put("Name", NameTextField.getText().trim());
        //if(!sciTextField.getText().isBlank())
            doc.put("sciName", sciTextField.getText().trim());
        if(!sizeTextField.getText().isBlank())
            doc.put("size", sizeTextField.getText().trim());
        if(!depth1TextField.getText().isBlank())
            doc.put("depth", depth1TextField.getText().trim() + "-" + depth2TextField.getText().trim());
        if(!akaTextField.getText().isBlank())
            doc.put("aka", toStringList(akaTextField.getText().split(",")));
        if(!asnTextField.getText().isBlank())
            doc.put("aSciName", toStringList(asnTextField.getText().split(",")));
        if(jTextField16.getText().equals("Endemic"))
            doc.put("endemic", true);
        if(!distTextField.getText().isBlank())
            doc.put("distribution", toStringList(distTextField.getText().split(",")));
        var list = new ArrayList<String>();
        if(!disp1TextField.getText().isBlank())
            list.add(disp1TextField.getText().trim());
        if(!disp2TextField.getText().isBlank())
            list.add(disp2TextField.getText().trim());
        if(!disp3TextField.getText().isBlank())
            list.add(disp3TextField.getText().trim());
        if( ! list.isEmpty())
            doc.put("dispNames", list);
        var listInt = new ArrayList<Integer>();
        if(!thumbTextField.getText().isBlank())
            listInt.add(Integer.parseInt(thumbTextField.getText().trim()));
        if(!thumb2TextField.getText().isBlank())
            listInt.add(Integer.parseInt(thumb2TextField.getText().trim()));
        if(!thumb3TextField.getText().isBlank())
            listInt.add(Integer.parseInt(thumb3TextField.getText().trim()));
        doc.put("thumbs", listInt);
        var listDoc = new ArrayList<Document>();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        for(int j = 0; j < model.getRowCount(); j++) {
            if(model.getValueAt(j, 0).toString().isBlank()) {
                continue;
            }
            String img = model.getValueAt(j, 0).toString().trim();
            String location = model.getValueAt(j, 1).toString().trim();
            String type = getString(model.getValueAt(j, 2));
            String comment = getString(model.getValueAt(j, 4));
            var p = new Document();
            p.put("id", Integer.parseInt(img));
            if(!location.isBlank())
                p.put("location", location);
            if(!type.isBlank())
                p.put("type", type);
            if(!comment.isBlank())
                p.put("comment", comment);
            listDoc.add(p);
        }
        doc.put("photos", listDoc);
        if(!noteTextField.getText().isBlank())
            doc.put("note", noteTextField.getText().trim());

        var rec = db.getMongoDB().getCollection("species").find(new Document("id", IDTextField.getText().trim())).first();
        if(rec != null && rec.getDate("update") != null) {
            Calendar cal = new GregorianCalendar();
            cal.add(Calendar.DAY_OF_MONTH, -30);
            if(rec.getDate("update").before(cal.getTime())) {
                System.out.println("Last saved: " + rec.getDate("update"));
                doc.put("update", new Date());
            } else {
                System.out.println("Saved less than 30 days ago");
                doc.put("update", rec.getDate("update"));
            }
        } else {
            System.out.println("No update tag");
            doc.put("update", new Date());
        }

        db.getMongoDB().getCollection("species").replaceOne(new Document("id", IDTextField.getText().trim()),
                doc, new ReplaceOptions().upsert(true));
        System.out.println("Saved " + IDTextField.getText());

//        var rec = db.getMongoDB().getCollection("species").find(new Document("id", IDTextField.getText().trim())).first();
//        rec.remove("update");
//        var cur = rec.toJson().replaceFirst("\"\\_id.*?\"\\}, ", "");
//        if(!cur.equals(doc.toJson())) {
//            System.out.println("**** NO MATCH " + IDTextField.getText().trim() + " *****");
//            System.out.println(cur);
//            System.out.println(doc.toJson());
//        }

//        node = new genReef35.Species(IDTextField.getText().trim(),NameTextField.getText().trim(),sciTextField.getText().trim(),sizeTextField.getText().trim()
//                ,depth1TextField.getText().trim() + "-" + depth2TextField.getText().trim(),node.endemic(),null, null,null,asnTextField.getText().trim()
//                ,akaTextField.getText().trim(),noteTextField.getText().trim(),null,null);


        try {
            String id = IDTextField.getText().trim();
            initDB();
            node = getNode(id);
        } catch(IOException ex) {
            Logger.getLogger(speciesEdit.class.getName()).log(Level.SEVERE, null, ex);
        }
        fillValues();

    }

    private <E> List<String> toStringList(E[] list) {
        List<String> ret = new ArrayList<>();
        for(var e : list) {
            ret.add(e.toString().trim());
        }
        return ret;
    }

    private String getString(Object o) {
        if(o == null)
            return "";
        return o.toString();
    }

    private void IDTextFieldActionPerformed(java.awt.event.ActionEvent evt) {
        if(NameTextField.getText().isEmpty())
            NameTextField.setText(IDTextField.getText());
    }

    private void loadButtonActionPerformed(java.awt.event.ActionEvent evt) {
        String[] list = db.species_collection.getAllSpecies().stream().map(s->s.id()).sorted().collect(Collectors.toList()).toArray(new String[0]);
        String sel = ListDialog.showDialog(rootPane, rootPane, list, IDTextField.getText());
        if(sel == null) {
            return;
        }
        loadSpecies(sel);
//        db.species_collection.getAllSpecies().forEach(s -> {
//            System.out.print('.');
//            loadSpecies(s.id());
//            saveButtonActionPerformed(null);
//        });

    }

    private void loadSpecies(String sel) {

        jMenuNewActionPerformed(null);
        node = getNode(sel);
        IDTextField.setText(sel);
        NameTextField.setText(node.name());
        jComboBox1.setSelectedItem("");
        sciTextField.setText(node.sciName());
        if(node.depth() != null && !node.depth().isEmpty()) {
            depth1TextField.setText(node.depth().split("-")[0]);
            depth2TextField.setText(node.depth().split("-")[1].split(" ")[0]);
        }
        if(node.size() != null && !node.size().isEmpty()) {
            sizeTextField.setText(node.size());
        }
        if((node.dispNames() == null) || node.dispNames().isEmpty()) {
            disp1TextField.setText("");
        } else {
            disp1TextField.setText(node.dispNames().get(0));
        }

        if(node.dispNames() != null && node.dispNames().size() >= 2) {
            disp2TextField.setText(node.dispNames().get(1));
        }
        else
            disp2TextField.setText("");
        if(node.dispNames() != null && node.dispNames().size() >= 3) {
            disp3TextField.setText(node.dispNames().get(2));
        }
        else
            disp3TextField.setText("");
        thumbTextField.setText((node.thumbs().size() >= 1) ? node.thumbs().get(0).toString() : "");
        thumb2TextField.setText((node.thumbs().size() >= 2) ? node.thumbs().get(1).toString() : "");
        thumb3TextField.setText((node.thumbs().size() >= 3) ? node.thumbs().get(2).toString() : "");
        akaTextField.setText(node.aka());
        asnTextField.setText(node.synonyms());
        distTextField.setText(node.dist().stream().collect(Collectors.joining(",")));

        //distTextField.setText("DistRAW");
        if(node.endemic())
                jTextField16.setText("Endemic");

        noteTextField.setText(node.note());
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        for(int j = 0; j < model.getRowCount(); j++) {
            for(int k = 0; k < model.getColumnCount(); k++) {
                model.setValueAt("", j, k);
            }
        }

        populateTable(node.photo());

    }

    final void populateTable(java.util.List<genReef35.photo> thumbList) {
        int colCount = jTable1.getColumnCount();
        javax.swing.table.TableColumn column;
        RowRenderer rowrend = new RowRenderer();
        for(int i = 0; i < colCount; i++) {
            column = jTable1.getColumn(jTable1.getColumnName(i));
            column.setCellRenderer(rowrend);
        }

        javax.swing.table.TableColumn tc = jTable1.getColumnModel().getColumn(0);
        tc.setPreferredWidth(50);
        tc.setMaxWidth(50);
        tc = jTable1.getColumnModel().getColumn(3);
        tc.setPreferredWidth(50);
        tc.setMaxWidth(50);
        tc = jTable1.getColumnModel().getColumn(2);
        tc.setPreferredWidth(130);
        tc.setMaxWidth(130);

        JComboBox com = new JComboBox<>(locations.toArray());
        jTable1.getColumnModel().getColumn(1).setCellEditor(new DefaultCellEditor(com));
        JComboBox com2 = new JComboBox<>(types.toArray());
        jTable1.getColumnModel().getColumn(2).setCellEditor(new DefaultCellEditor(com2));

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int i = 0;
        if(thumbList != null) {
            for(genReef35.photo tl : thumbList) {
                model.setValueAt(tl.id(), i, 0);
                model.setValueAt(tl.location(), i, 1);
                model.setValueAt(tl.type(), i, 2);
                model.setValueAt("", i, 3);
                model.setValueAt(tl.comment(), i++, 4);

//                model.setValueAt(db.getField(tl, 0), i, 0);
//                model.setValueAt(db.getField(tl, 1), i, 1);
//                model.setValueAt(db.getField(tl, 3), i, 2);
//                model.setValueAt(db.getField(tl, 2), i, 3);
//                model.setValueAt(db.getField(tl, 4), i++, 4);
            }
        }





    }

    private void depth1TextFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void depth2TextFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {
        sciTextField.setText((String) jComboBox1.getSelectedItem());
    }

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {
    }

    private void sizeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void thumbTextFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void thumb2TextFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void thumb3TextFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void distSelectActionPerformed(java.awt.event.ActionEvent evt) {
        ArrayList<String> possibleValues = new ArrayList<>(dist_a);
        String[] initialValues;
        if((node == null) || (node.dist() == null) || node.dist().isEmpty()) {
            initialValues = new String[0];
        } else {
            String[] sel = node.dist().toArray(String[]::new); //node.distributionRaw.split(",");
            for(String sel1 : sel) {
                possibleValues.remove(sel1.trim());;
            }
            initialValues = node.dist().toArray(String[]::new);
        }
        var ret = distDialog.showDialog(rootPane, rootPane, null, null, possibleValues, new ArrayList<>(Arrays.asList(initialValues)));
        if(ret == null)
            return;
        distTextField.setText(ret.stream().collect(Collectors.joining(",")));
        if(node != null) {
            node.dist().removeAll(node.dist());
            node.dist().addAll(ret);
        }
    }

    private void jMenuNewActionPerformed(java.awt.event.ActionEvent evt) {
        IDTextField.setText("");
        NameTextField.setText("");
        jComboBox1.setSelectedItem("");
        sciTextField.setText("");
        depth1TextField.setText("");
        depth2TextField.setText("");
        sizeTextField.setText("");
        disp1TextField.setText("");
        disp2TextField.setText("");
        disp3TextField.setText("");
        thumbTextField.setText("");
        thumb2TextField.setText("");
        thumb3TextField.setText("");
        akaTextField.setText("");
        asnTextField.setText("");
        distTextField.setText("");
        jTextField16.setText("");
        noteTextField.setText("");
        try {
            initDB();
        } catch(IOException ex) {
            Logger.getLogger(speciesEdit.class.getName()).log(Level.SEVERE, null, ex);
        }
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        for(int j = 0; j < model.getRowCount(); j++) {
            for(int k = 0; k < model.getColumnCount(); k++) {
                model.setValueAt("", j, k);
            }
        }
        model.setValueAt("1", 0, 0);
        thumbTextField.setText("1");
        node = null;
    }

    private void NameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {
        //if(disp1TextField.getText().isEmpty())
        // disp1TextField.setText(NameTextField.getText());
    }

    private void NameTextFieldFocusLost(java.awt.event.FocusEvent evt) {
        NameTextFieldActionPerformed(null);
    }

    private void IDTextFieldFocusLost(java.awt.event.FocusEvent evt) {
        IDTextFieldActionPerformed(null);
    }

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {
        showPopup(evt);
    }

    private void jTable1MouseReleased(java.awt.event.MouseEvent evt) {
        showPopup(evt);
    }

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {
        System.out.println("XXX " + row);
        if(node == null)
            return;
        if(row == 0)
            return;
        if(node.photo().size() <= row)
            return;

        genReef35.photo up =  node.photo().get(row);
        genReef35.photo down = node.photo().get(row - 1);
        node.photo().set(row, down);
        node.photo().set(row - 1, up);
        populateTable(node.photo());


    }

    private void showPopup(java.awt.event.MouseEvent e) {
        if(e.isPopupTrigger()) {
            final int col = jTable1.columnAtPoint(e.getPoint());
            final int l_row = jTable1.rowAtPoint(e.getPoint());
            this.row = l_row;
            System.out.println(l_row);
            jPopupMenu1.show(e.getComponent(), e.getX(), e.getY());
        }
    }


    genReef35.Species getNode(String name) {
        return db.species_collection.getSpecies(name);
    }

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new speciesEdit().setVisible(true);
            } catch(IOException ex) {
                Logger.getLogger(speciesEdit.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }
    // Variables declaration - do not modify
    private javax.swing.JTextField IDTextField;
    private javax.swing.JTextField NameTextField;
    private javax.swing.JTextField akaTextField;
    private javax.swing.JTextField asnTextField;
    private javax.swing.JTextField depth1TextField;
    private javax.swing.JTextField depth2TextField;
    private javax.swing.JTextField disp1TextField;
    private javax.swing.JTextField disp2TextField;
    private javax.swing.JTextField disp3TextField;
    private javax.swing.JButton distSelect;
    private javax.swing.JTextField distTextField;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuNew;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JButton loadButton;
    private javax.swing.JTextField noteTextField;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextField sciTextField;
    private javax.swing.JTextField sizeTextField;
    private javax.swing.JTextField thumb2TextField;
    private javax.swing.JTextField thumb3TextField;
    private javax.swing.JTextField thumbTextField;
    // End of variables declaration
}
